import { Injectable } from "@nestjs/common";
import { AiCapability } from "@prisma/client";
import { AiProvider, AiProviderRequest, AiProviderResponse } from "./ai-provider.interface";

@Injectable()
export class StubAiProviderService implements AiProvider {
  async run(request: AiProviderRequest): Promise<AiProviderResponse> {
    const started = Date.now();

    const input = request.input ?? {};
    const fileName = typeof input["fileName"] === "string" ? input["fileName"] : "";
    const fileNameLower = fileName.toLowerCase();

    let output: Record<string, unknown>;

    const looksLikeInvoice = /\binvoice\b|rechnung|bill/.test(fileNameLower);

    if (request.capability === AiCapability.DOCUMENT_ANALYSIS) {
      output = {
        documentType: looksLikeInvoice ? "invoice" : "unknown",
        confidence: looksLikeInvoice ? 0.92 : 0.55,
        reasoning: looksLikeInvoice
          ? "Filename suggests an invoice-like document."
          : "Insufficient signals in stub mode; defaulting to unknown."
      };
    } else if (request.capability === AiCapability.INVOICE_ANALYSIS) {
      output = {
        invoiceNumber: looksLikeInvoiceNumber(fileName),
        invoiceDate: "2026-04-01",
        dueDate: "2026-04-15",
        vendorName: "Stub Vendor GmbH",
        totalAmount: 1234.56,
        currency: "EUR",
        lineItems: [
          {
            description: "Stub line item",
            quantity: 1,
            unitPrice: 1234.56,
            lineTotal: 1234.56
          }
        ],
        confidence: 0.7
      };
    } else {
      output = {
        provider: request.providerName,
        model: request.modelName,
        capability: request.capability,
        echoedInput: request.input,
        suggestions: [
          {
            type: "GENERIC",
            summary: `Stub suggestion for capability ${request.capability}`,
            rationale: "Generated by local stub provider"
          }
        ]
      };
    }

    const latencyMs = Math.max(1, Date.now() - started);
    const confidenceScore =
      typeof output["confidence"] === "number" ? (output["confidence"] as number) : 0.5;
    return {
      output,
      confidenceScore,
      latencyMs,
      providerMetadata: {
        stub: true,
        tokenUsage: { promptTokens: 0, completionTokens: 0 }
      }
    };
  }
}

function looksLikeInvoiceNumber(fileName: string): string {
  const match = fileName.match(/(\d{4,})/);
  return match ? `INV-${match[1]}` : "INV-0001";
}
