import { Injectable } from "@nestjs/common";
import { AiProvider, AiProviderRequest, AiProviderResponse } from "./ai-provider.interface";

@Injectable()
export class StubAiProviderService implements AiProvider {
  async run(request: AiProviderRequest): Promise<AiProviderResponse> {
    const started = Date.now();

    const suggestions = [
      {
        type: "GENERIC",
        summary: `Stub suggestion for capability ${request.capability}`,
        rationale: "Generated by local stub provider"
      }
    ];

    const output: Record<string, unknown> = {
      provider: request.providerName,
      model: request.modelName,
      capability: request.capability,
      echoedInput: request.input,
      suggestions
    };

    const latencyMs = Math.max(1, Date.now() - started);
    return {
      output,
      confidenceScore: 0.5,
      latencyMs,
      providerMetadata: {
        stub: true,
        tokenUsage: { promptTokens: 0, completionTokens: 0 }
      }
    };
  }
}
